aws_region            = "us-east-1"
environment           = "production"
project_name          = "drug-app"
vpc_cidr              = "10.0.0.0/16"
public_subnet_cidr    = "10.0.1.0/24"
private_subnet_cidrs  = ["10.0.10.0/24", "10.0.11.0/24"]
instance_type         = "t3.medium"
min_nodes             = 2
max_nodes             = 5
desired_nodes         = 2
